export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";
export const LOGGED_IN = "LOGGED_IN";

export const STUDENTS_FETCH = "STUDENTS_FETCH";
export const STUDENTS_FETCH_SUCCESS = "STUDENTS_FETCH_SUCCESS";

export const STUDENT_SELECT = "STUDENT_SELECT";
export const STUDENT_CHANGE = "STUDENT_CHANGE";
export const STUDENT_CREATE = "STUDENT_CREATE";
export const STUDENT_SAVE_SUCCESS = "STUDENT_SAVE_SUCCESS";
export const STUDENT_DELETE_SUCCESS = "STUDENT_DELETE_SUCCESS";
export const STUDENT_DESELECT = "STUDENT_DESELECT";

export const APPOINTMENTS_FETCH = "APPOINTMENTS_FETCH";
export const APPOINTMENTS_FETCH_SUCCESS = "APPOINTMENTS_FETCH_SUCCESS";
export const APPOINTMENTS_STUDENT_NUMBER ="APPOINTMENTS_STUDENT_NUMBER";
export const APPOINTMENTS_STUDENT = "APPOINTMENTS_STUDENT";

export const APPOINTMENT_CHANGE = "APPOINTMENT_CHANGE";
export const APPOINTMENT_CREATE = "APPOINTMENT_CREATE";
export const APPOINTMENT_SAVE_SUCCESS = "APPOINTMENT_SAVE_SUCCESS";

export const PROJECT_TYPES = "PROJECT_TYPES";
export const NUMBER_OF_APPOINTMENTS = "NUMBER_OF_APPOINTMENTS";
export const ATTENDANCE = "ATTENDANCE";
export const STUDENTS_PER_DAY = "STUDENTS_PER_DAY";
export const STUDENTS_PER_MONTH = "STUDENTS_PER_MONTH";
export const STUDENTS_PER_PROJECT = "STUDENTS_PER_PROJECT";