export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";
export const LOGGED_IN = "LOGGED_IN";

export const STUDENTS_FETCH_SUCCESS = "STUDENTS_FETCH_SUCCESS";

export const STUDENT_SELECT = "STUDENT_SELECT";
export const STUDENT_CHANGE = "STUDENT_CHANGE";
export const STUDENT_CREATE = "STUDENT_CREATE";
export const STUDENT_SAVE_SUCCESS = "STUDENT_SAVE_SUCCESS";
export const STUDENT_DELETE_SUCCESS = "STUDENT_DELETE_SUCCESS";
export const STUDENT_DESELECT = "STUDENT_DESELECT";
